# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddMemberDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddMemberDialog(object):
    def setupUi(self, AddMemberDialog):
        AddMemberDialog.setObjectName("AddMemberDialog")
        AddMemberDialog.resize(255, 268)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        AddMemberDialog.setFont(font)
        AddMemberDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        AddMemberDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.verticalLayout = QtWidgets.QVBoxLayout(AddMemberDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flay_info = QtWidgets.QFormLayout()
        self.flay_info.setObjectName("flay_info")
        self.lbl_fname = QtWidgets.QLabel(AddMemberDialog)
        self.lbl_fname.setObjectName("lbl_fname")
        self.flay_info.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_fname)
        self.lbl_lname = QtWidgets.QLabel(AddMemberDialog)
        self.lbl_lname.setObjectName("lbl_lname")
        self.flay_info.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_lname)
        self.lbl_phone = QtWidgets.QLabel(AddMemberDialog)
        self.lbl_phone.setObjectName("lbl_phone")
        self.flay_info.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_phone)
        self.lbl_address = QtWidgets.QLabel(AddMemberDialog)
        self.lbl_address.setObjectName("lbl_address")
        self.flay_info.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_address)
        self.txt_fname = QtWidgets.QLineEdit(AddMemberDialog)
        self.txt_fname.setClearButtonEnabled(True)
        self.txt_fname.setObjectName("txt_fname")
        self.flay_info.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_fname)
        self.txt_lname = QtWidgets.QLineEdit(AddMemberDialog)
        self.txt_lname.setClearButtonEnabled(True)
        self.txt_lname.setObjectName("txt_lname")
        self.flay_info.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_lname)
        self.txt_phone = QtWidgets.QLineEdit(AddMemberDialog)
        self.txt_phone.setClearButtonEnabled(True)
        self.txt_phone.setObjectName("txt_phone")
        self.flay_info.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_phone)
        self.txt_address = QtWidgets.QLineEdit(AddMemberDialog)
        self.txt_address.setClearButtonEnabled(True)
        self.txt_address.setObjectName("txt_address")
        self.flay_info.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_address)
        self.verticalLayout.addLayout(self.flay_info)
        self.lbl_error = QtWidgets.QLabel(AddMemberDialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_error.setPalette(palette)
        self.lbl_error.setObjectName("lbl_error")
        self.verticalLayout.addWidget(self.lbl_error)
        self.hlay_buttons = QtWidgets.QHBoxLayout()
        self.hlay_buttons.setObjectName("hlay_buttons")
        self.btn_add = QtWidgets.QPushButton(AddMemberDialog)
        self.btn_add.setObjectName("btn_add")
        self.hlay_buttons.addWidget(self.btn_add)
        self.btn_back = QtWidgets.QPushButton(AddMemberDialog)
        self.btn_back.setObjectName("btn_back")
        self.hlay_buttons.addWidget(self.btn_back)
        self.verticalLayout.addLayout(self.hlay_buttons)

        self.retranslateUi(AddMemberDialog)
        QtCore.QMetaObject.connectSlotsByName(AddMemberDialog)

    def retranslateUi(self, AddMemberDialog):
        _translate = QtCore.QCoreApplication.translate
        AddMemberDialog.setWindowTitle(_translate("AddMemberDialog", "افزودن عضو"))
        self.lbl_fname.setText(_translate("AddMemberDialog", "نام"))
        self.lbl_lname.setText(_translate("AddMemberDialog", "نام خانوادگی"))
        self.lbl_phone.setText(_translate("AddMemberDialog", "تلفن"))
        self.lbl_address.setText(_translate("AddMemberDialog", "آدرس"))
        self.lbl_error.setText(_translate("AddMemberDialog", "خطا"))
        self.btn_add.setText(_translate("AddMemberDialog", "ثبت عضو"))
        self.btn_back.setText(_translate("AddMemberDialog", "بازگشت"))
