# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LoginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(240, 192)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        LoginDialog.setFont(font)
        LoginDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        LoginDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flay_inputs = QtWidgets.QFormLayout()
        self.flay_inputs.setObjectName("flay_inputs")
        self.lbl_username = QtWidgets.QLabel(LoginDialog)
        self.lbl_username.setObjectName("lbl_username")
        self.flay_inputs.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_username)
        self.txt_username = QtWidgets.QLineEdit(LoginDialog)
        self.txt_username.setClearButtonEnabled(True)
        self.txt_username.setObjectName("txt_username")
        self.flay_inputs.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_username)
        self.lbl_password = QtWidgets.QLabel(LoginDialog)
        self.lbl_password.setObjectName("lbl_password")
        self.flay_inputs.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_password)
        self.txt_password = QtWidgets.QLineEdit(LoginDialog)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setClearButtonEnabled(True)
        self.txt_password.setObjectName("txt_password")
        self.flay_inputs.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_password)
        self.verticalLayout.addLayout(self.flay_inputs)
        self.lbl_error = QtWidgets.QLabel(LoginDialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_error.setPalette(palette)
        self.lbl_error.setObjectName("lbl_error")
        self.verticalLayout.addWidget(self.lbl_error)
        self.hlay_rdb = QtWidgets.QHBoxLayout()
        self.hlay_rdb.setObjectName("hlay_rdb")
        self.rdb_member = QtWidgets.QRadioButton(LoginDialog)
        self.rdb_member.setChecked(True)
        self.rdb_member.setObjectName("rdb_member")
        self.hlay_rdb.addWidget(self.rdb_member)
        self.rdb_employee = QtWidgets.QRadioButton(LoginDialog)
        self.rdb_employee.setObjectName("rdb_employee")
        self.hlay_rdb.addWidget(self.rdb_employee)
        self.verticalLayout.addLayout(self.hlay_rdb)
        self.hlay_buttons = QtWidgets.QHBoxLayout()
        self.hlay_buttons.setObjectName("hlay_buttons")
        self.btn_login = QtWidgets.QPushButton(LoginDialog)
        self.btn_login.setObjectName("btn_login")
        self.hlay_buttons.addWidget(self.btn_login)
        self.btn_back = QtWidgets.QPushButton(LoginDialog)
        self.btn_back.setObjectName("btn_back")
        self.hlay_buttons.addWidget(self.btn_back)
        self.verticalLayout.addLayout(self.hlay_buttons)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "ورود به صفحه کاربری"))
        self.lbl_username.setText(_translate("LoginDialog", "نام کاربری"))
        self.lbl_password.setText(_translate("LoginDialog", "رمز عبور"))
        self.lbl_error.setText(_translate("LoginDialog", "خطا"))
        self.rdb_member.setText(_translate("LoginDialog", "عضو"))
        self.rdb_employee.setText(_translate("LoginDialog", "کارمند"))
        self.btn_login.setText(_translate("LoginDialog", "ورود"))
        self.btn_back.setText(_translate("LoginDialog", "بازگشت"))
