# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QuestionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuestionDialog(object):
    def setupUi(self, QuestionDialog):
        QuestionDialog.setObjectName("QuestionDialog")
        QuestionDialog.resize(327, 90)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QuestionDialog.sizePolicy().hasHeightForWidth())
        QuestionDialog.setSizePolicy(sizePolicy)
        QuestionDialog.setMinimumSize(QtCore.QSize(0, 90))
        QuestionDialog.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        QuestionDialog.setFont(font)
        QuestionDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        QuestionDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.verticalLayout = QtWidgets.QVBoxLayout(QuestionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_message = QtWidgets.QLabel(QuestionDialog)
        self.lbl_message.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_message.setObjectName("lbl_message")
        self.verticalLayout.addWidget(self.lbl_message)
        self.hlay_buttons = QtWidgets.QHBoxLayout()
        self.hlay_buttons.setObjectName("hlay_buttons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlay_buttons.addItem(spacerItem)
        self.btn_confirm = QtWidgets.QPushButton(QuestionDialog)
        self.btn_confirm.setObjectName("btn_confirm")
        self.hlay_buttons.addWidget(self.btn_confirm)
        self.btn_back = QtWidgets.QPushButton(QuestionDialog)
        self.btn_back.setObjectName("btn_back")
        self.hlay_buttons.addWidget(self.btn_back)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlay_buttons.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.hlay_buttons)

        self.retranslateUi(QuestionDialog)
        QtCore.QMetaObject.connectSlotsByName(QuestionDialog)

    def retranslateUi(self, QuestionDialog):
        _translate = QtCore.QCoreApplication.translate
        QuestionDialog.setWindowTitle(_translate("QuestionDialog", "سوال"))
        self.lbl_message.setText(_translate("QuestionDialog", "متن سوال؟"))
        self.btn_confirm.setText(_translate("QuestionDialog", "تایید"))
        self.btn_back.setText(_translate("QuestionDialog", "بازگشت"))
