# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ShowEmployeesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowEmployeesDialog(object):
    def setupUi(self, ShowEmployeesDialog):
        ShowEmployeesDialog.setObjectName("ShowEmployeesDialog")
        ShowEmployeesDialog.resize(530, 400)
        ShowEmployeesDialog.setMinimumSize(QtCore.QSize(530, 400))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        ShowEmployeesDialog.setFont(font)
        ShowEmployeesDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        ShowEmployeesDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.verticalLayout = QtWidgets.QVBoxLayout(ShowEmployeesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbl_employees = QtWidgets.QTableWidget(ShowEmployeesDialog)
        self.tbl_employees.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_employees.setObjectName("tbl_employees")
        self.tbl_employees.setColumnCount(5)
        self.tbl_employees.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        item.setFont(font)
        self.tbl_employees.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        item.setFont(font)
        self.tbl_employees.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        item.setFont(font)
        self.tbl_employees.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        item.setFont(font)
        self.tbl_employees.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        item.setFont(font)
        self.tbl_employees.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tbl_employees)
        self.hlay_buttons = QtWidgets.QHBoxLayout()
        self.hlay_buttons.setObjectName("hlay_buttons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlay_buttons.addItem(spacerItem)
        self.btn_back = QtWidgets.QPushButton(ShowEmployeesDialog)
        self.btn_back.setObjectName("btn_back")
        self.hlay_buttons.addWidget(self.btn_back)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlay_buttons.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.hlay_buttons)

        self.retranslateUi(ShowEmployeesDialog)
        QtCore.QMetaObject.connectSlotsByName(ShowEmployeesDialog)

    def retranslateUi(self, ShowEmployeesDialog):
        _translate = QtCore.QCoreApplication.translate
        ShowEmployeesDialog.setWindowTitle(_translate("ShowEmployeesDialog", "لیست مسئولان کتابخانه"))
        item = self.tbl_employees.horizontalHeaderItem(0)
        item.setText(_translate("ShowEmployeesDialog", "کد مسئول"))
        item = self.tbl_employees.horizontalHeaderItem(1)
        item.setText(_translate("ShowEmployeesDialog", "نام"))
        item = self.tbl_employees.horizontalHeaderItem(2)
        item.setText(_translate("ShowEmployeesDialog", "نام خانوادگی"))
        item = self.tbl_employees.horizontalHeaderItem(3)
        item.setText(_translate("ShowEmployeesDialog", "تلفن"))
        item = self.tbl_employees.horizontalHeaderItem(4)
        item.setText(_translate("ShowEmployeesDialog", "بخش"))
        self.btn_back.setText(_translate("ShowEmployeesDialog", "بازگشت"))
